### PR TITLE
GotoDialog testing correctly input field text

### PR DESCRIPTION
**Pull request by pvmm**

### CODE REVIEW

**Comment by Colpocorto** [comment]
It seems only the 32bit Windows version has been built. Is it possible to make a 64bit build with this change?

**Comment by andete** [comment]
> It seems only the 32bit Windows version has been built. Is it possible to make a 64bit build with this change?

Hello, the mingw32 build is actually a 64bit mingw32 build normally.

**Comment by Colpocorto** [comment]
> > It seems only the 32bit Windows version has been built. Is it possible to make a 64bit build with this change?
> 
> Hello, the mingw32 build is actually a 64bit mingw32 build normally.

Why does a x86_64-mingw build also exist, then?

**Comment by MBilderbeek** [comment]
Not sure how these files from Jan 27 have been built... I guess these are the left-overs that are mentioned in #172 ? Anyways, the ming32 one is indeed 64-bit, use that one please.

**Pull request merged**
