### PR TITLE
VS 2015 project for openmsx-debugger

### PR DESCRIPTION
**Pull request by mfeingol**
This PR provides a VS 2015 project that builds the openmsx debugger as a 64-bit binary.

There are still some things left to do:

1. Get the 32-bit build working as well. I only installed and built the 64-bit qt bits. Depending on the paths chosen by the qt folks, the `ThirdPartySrcDir` variable in `openmsx-debugger.props` may need to be changed.
2. Scripting installation of the (massive) qt bits, or putting together some kind of manual package with only the bits we need.
3. Anything post-build - i.e. putting the executable together with the DLLs into some kind of package.

### CODE REVIEW

**Comment by MBilderbeek** [comment]
I'll already merge this part, as it is better than what we have now.

I hope you have some time to do these other parts, as it will make it vastly easier for Patrick to create an automatic build on the debugger.

**Comment by MBilderbeek** [comment]
Oh, before I merge it one question: why the change in GotoDialog.h?

**Comment by mfeingol** [comment]
I was actually hoping Patrick could take it from here. :-)

It was some days ago, but IIRC GOTODIALOG_H was being defined by something else as well, leading to non-inclusion and build errors. You can probably undo that change and reproduce those errors.

**Comment by MBilderbeek** [comment]
It compiles fine on Linux. Also, I can't find a double definition really:
```
~/git/debugger.git$ grep GOTODIALOG * -r
derived/src/ui_GotoDialog.h:#ifndef UI_GOTODIALOG_H
derived/src/ui_GotoDialog.h:#define UI_GOTODIALOG_H
derived/src/ui_GotoDialog.h:#endif // UI_GOTODIALOG_H
src/GotoDialog.h:#ifndef GOTODIALOG_H
src/GotoDialog.h:#define GOTODIALOG_H
src/GotoDialog.h:#endif // GOTODIALOG_H
```

See the prefixes in the generated code?

As for picking it up further: only Patrick can tell us if he's able to do that...

**Comment by mfeingol** [comment]
On Windows I see this:

```
W:\Build\openmsx\debugger>findstr -si GOTODIALOG_H *.h
src\GotoDialog.h:#ifndef GOTODIALOG_H
src\GotoDialog.h:#define GOTODIALOG_H
src\GotoDialog.h:#endif // GOTODIALOG_H
src\ui\ui_GotoDialog.h:#ifndef GOTODIALOG_H
src\ui\ui_GotoDialog.h:#define GOTODIALOG_H
src\ui\ui_GotoDialog.h:#endif // GOTODIALOG_H
```

**Comment by mthuurne** [comment]
On Friday 18 November 2016 16:00:15 Max Feingold wrote:
> On Windows I see this:
> 
> ```
> W:\Build\openmsx\debugger>findstr -si GOTODIALOG_H *.h
> src\GotoDialog.h:#ifndef GOTODIALOG_H
> src\GotoDialog.h:#define GOTODIALOG_H
> src\GotoDialog.h:#endif // GOTODIALOG_H
> src\ui\ui_GotoDialog.h:#ifndef GOTODIALOG_H
> src\ui\ui_GotoDialog.h:#define GOTODIALOG_H
> src\ui\ui_GotoDialog.h:#endif // GOTODIALOG_H
> ```

On my machine (Linux), in ui_GotoDialog.h the include guard is 
"UI_GOTODIALOG_H". So it seems something went wrong in the generation of 
the UI headers on your machine.

I'm using Qt 5.7.0. The command that runs uic is:

/usr/lib64/qt5/bin/uic -o derived/src/ui_GotoDialog.h src/GotoDialog.ui

Bye,
		Maarten

**Comment by mfeingol** [comment]
Ah, I see. Our scripts were using `>` instead of `-o`. Fixed.

**Comment by MBilderbeek** [comment]
Cool, can you update the pull request?

**Comment by mfeingol** [comment]
Already done.

**Comment by MBilderbeek** [comment]
Ah, sorry, I didn't see that, in another pull request it was shown as a separate commit. I'll merge it, it's at least a lot better than what we had before. But I hope you can still continue a bit on the open points.

**Comment by mfeingol** [comment]
Yeah, I just amended and force-pushed. But truly hoping others can take it from here.

**Comment by MBilderbeek** [comment]
Well, you can hope, but I don't think that will lead to anything... :P Perhaps you can contact Patrick specifically to ask him to continue a bit and offer him some starting points?

**Pull request merged**
