### PR TITLE
support labels in BreakpointViewer

### PR DESCRIPTION
**Pull request by pvmm**
image

### CODE REVIEW

**Review by m9710797 — COMMENTED** [review]
Hi,
I did a quick review-pass, just looking for general c++ stuff. I did not yet try to understand what the code is actually doing. Nor did I try to run the code. And I won't have time for that today.

**Comment by pvmm** [comment]
> I see in the Symbol class that symbols can have a type. Maybe this substitution should only be done for symbols of type JUMPLABEL?

And this also: there is no function in SymbolTable that helps me do this kind of type filtering.

**Comment by m9710797** [comment]
I agree that you only occasionally want to see the numeric value. So cluttering the output with an extra column is not a good solution. Maybe a popup message could be a solution (when you hover the mouse pointer over the label)? I don't know if that is easy to do in a table in Qt.

IMHO it would be nice if addresses/labels behave the same everywhere (as much as possible) in the debugger. So in the disassembly view, in the breakpoint viewer, any other widgets?

(If you want I can already accept your patch before these changes (popup message). But after you fixed yesterdays review comments.)

**Comment by pvmm** [comment]
> IMHO it would be nice if addresses/labels behave the same everywhere (as much as possible) in the debugger. So in the disassembly view, in the breakpoint viewer, any other widgets?

Maybe in Main Memory when VARIABLELABEL is properly implemented as a popup message.

**Comment by pvmm** [comment]
`BreakpointViewer::setTextField()` now has a tooltip parameter.

**Comment by m9710797** [comment]
Thanks!

**Comment by pvmm** [comment]
Hosting screenshot for MSX Resource Center.
image

**Pull request merged**
