### PR TITLE
unravelling the code of DisasmViewer

### PR DESCRIPTION
**Pull request by pvmm**
* seems like this fix actually solves minor issue in #102 (PC's cursor moving out of the screen);
* replacing `quint16` with `uint16_t` in the affected areas (and scary `unsigned short` too);
* This PR needs #108 to be merged;

### CODE REVIEW

**Comment by pvmm** [comment]
This PR needs #108 to continue.

**Comment by m9710797** [comment]
Looks good to me. (From a c++ point of view, I didn't actually compile/run the code).
I'll merge once you mark this PR 'ready'.

**Comment by pvmm** [comment]
Extra changes:
* new style signal/slot connection is used in DebuggerForm.cpp which tests if functions and signals exist and returns compile error if they don't;
* regrouping and reordering of signal/slot connections in single place;
* new functions `onSlotsChecked` and `onPcChanged` are used to update `disasmviewer`, because there are two widgets competing to update `disasmview` (`slotView` and `regsView`), producing weird behaviours. These functions make `disasmviewer` only update once.

**Comment by m9710797** [comment]
Very nice. I've always disliked the fact that typos in signal/slot-connect stuff is only detected at run-time rather than compile-time.
I'll gladly accepts patches that convert even more signal/slot connect calls.

Does this mean that (in the future) we can also remove the "slot" annotations in the .h files?

**Comment by pvmm** [comment]
> Does this mean that (in the future) we can also remove the "slot" annotations in the .h files?

Yes. Only "signals:" still needed

**Comment by m9710797** [comment]
Thanks.

**Pull request merged**
